name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please do a search of existing issues.
  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        A detailed, step-by-step description of how to reproduce the issue is required. 
        If possible, provide a link to a repository or project where the issue can be reproduced.
      placeholder: |
        1. Create a application
        2. Click X
        3. Y will happen

        Make sure to:
        - Use numbered lists to outline steps clearly.
        - Include all relevant commands and configurations.
        - Provide a link to a reproducible repository if applicable.
    validations:
      required: true
