name: Feature Request
description: Suggest a new feature or improvement to the project
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the enhancement
      description: The description of what this enhancement is.
      placeholder: Add X to the core
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What is the priority for this change?
      description: Let us know the priority for this change.
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true
