name: Lint Project

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: NODE_OPTIONS="--max-old-space-size=4096" pnpm install

      - run: pnpm run lint
